name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: 
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: reportedBy
    attributes:
      label: Reported by 
      description: Reporter of the issue
      placeholder: UserName
    validations:
      required: true  
  - type: input
    id: reportedByStore
    attributes:
      label: Reported by Store 
      description: Please input store number
      placeholder: Store Number
    validations:
      required: true
  - type: dropdown
    id: bugTypes
    attributes:
      label: Bug Type
      multiple: true
      options:
        - UI/UX
        - Functional
        - Performance Issues
        - Compatibility
        - Networking Errors
        - Crashes and Stability Problems
        - Localization Issues
        - Others
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: appFeature
    attributes:
      label: App Feature
      description: At what point issue was experienced?
      options:
        - DSD Purchase Orders
        - Coin Ordering
        - Delivery Reception
        - Box Label Error
        - Others
      default: 0
    validations:
      required: false
  - type: textarea
    id: stepsToReproduce
    attributes:
      label: Steps to reproduce
      description: Please provide step by step process to reproduce the issue.
      placeholder: Steps
      value: "Step 1:"
    validations:
      required: false
